---
# run info
run_name: "dqn"
n_episodes: 50
seed: 42

# training
buffer_size: 100000
batch_size: 32
update_every: 8
learning_rate: 0.0005
tau: 0.001
gamma: 0.99
buffer_min_size: 0
hidden_size: 256
use_gpu: false

# exploration vs. exploitation
eps_start: 1.0
eps_end: 0.01
eps_decay: 0.995    # for 2500 timesteps