---
# run info
n_episodes: 50
seed: 42
n_workers: 1
max_optimisation_steps: 1000

# Learner Config
learner_config:
    run_name: "FNN_cartpole"
    max_steps: 500
    max_steps_per_episode: 200
    target_updates: 100
    samples_per_update: 256
    batch_size: 128
    IS: false
    log_interval: 10
    n_workers: 2
    optimiser_config:
      type: "adam"
      learning_rate: 3e-4
    n_epochs_update: 4


# Controller Config
controller_config:
    action_size: 2
    gae_horizon: 16
    gamma: 0.99
    lam: 0.95
    clip_epsilon: 0.2
    value_loss_coefficient: 0.5
    entropy_coefficient: 0.01
    tau: 0.99
    n_features: 4
    actor_config:
      type: "FNN"
      layer_sizes:
      - 128
      - 64
    critic_config:
      type: "FNN"
      layer_sizes:
      - 128
      - 64


# Environment Config
environment_config:
    type: gym
    id: CartPole-v1
    env_kwargs: {}
